after-login-command = []

after-startup-command = [
  'exec-and-forget /etc/profiles/per-user/smissingham/sketchybar',
  'exec-and-forget /etc/profiles/per-user/smissingham/bin/borders',
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = false

# Mouse lazily follows any focus (window or workspace)
on-focus-changed = ['move-mouse window-lazy-center']

[[on-window-detected]]
if.app-name-regex-substring = 'Finder'
run = 'layout floating'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 24
inner.vertical = 24
outer.left = 12
outer.bottom = 12
outer.top = 12
outer.right = 12

[mode.main.binding]
