[default_session]
#startup_command = "$EDITOR -c ':lua Snacks.picker.recent()'"
preview_command = "eza --all --git --icons --color=always --tree --level=2 {}"

[[session]]
name = "Nix â„ï¸"
path = "~/Documents/Nix"

[[session]]
name = "Notes"
path = "~/Documents/Obsidian/second-brain"
startup_command = "sv"

[[session]]
name = "Employer ğŸ‘”"
path = "~/Documents/Employer"

[[session]]
name = "Download ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"
