[default_session]
startup_command = "$EDITOR -c ':lua Snacks.picker.recent()'"

[[session]]
name = "Config ðŸ”§"
path = "~/Documents/Nix"

[[session]]
name = "Download ðŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Employer ðŸ‘”"
path = "~/Documents/Employer"
