[default_session]
startup_command = "$EDITOR -c ':lua Snacks.picker.smart()'"

[[session]]
name = "Nix â„ï¸"
path = "~/Documents/Nix"

[[session]]
name = "Download ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"
